version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/basis/backend/php/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    env_file:
      - .env
    working_dir: /code
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/code:delegated,rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - basis

  web:
    image: nginx:1.22.0
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./docker/basis/backend/nginx/basis-php.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - basis

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - basis

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - basis

networks:
  basis:
    name: basis
    driver: bridge
